/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 ../../../public/aguapunteras.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function AguapunteraModel(props) {
  const { nodes, materials } = useGLTF('/aguapunteras.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.aguapunteras.geometry} material={materials.Mat_1} />
    </group>
  )
}

useGLTF.preload('/aguapunteras.gltf')
