/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 ./pieza2.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Pieza2(props) {
  const { nodes, materials } = useGLTF('/pieza2.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Ensamblaje1_-_Pieza2-8'].geometry} material={materials.Mat_1} />
    </group>
  )
}

useGLTF.preload('/pieza2.gltf')
