/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 ./pieza9.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Pieza9(props) {
  const { nodes, materials } = useGLTF('/pieza9.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['radiador-FLX-01'].geometry} material={materials.Mat_1} />
    </group>
  )
}

useGLTF.preload('/pieza9.gltf')
