/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 ./pieza6.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Pieza6(props) {
  const { nodes, materials } = useGLTF('/pieza6.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Ensamblaje1_-_pieza6-1'].geometry} material={materials.Mat_1} />
    </group>
  )
}

useGLTF.preload('/pieza6.gltf')
