/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 ./pieza8.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Pieza8(props) {
  const { nodes, materials } = useGLTF('/pieza8.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Placa_refrigeracion.geometry} material={materials.Mat_1} />
    </group>
  )
}

useGLTF.preload('/pieza8.gltf')
